### ISSUE TITLE
3/10 libraries are not really threadsafe

### ISSUE THREAD

**Issue by sergey-shambir** [NoAvailableAlias/signal-slot-benchmarks#10]
* [Kosta-Github/signals-cpp](https://github.com/Kosta-Github/signals-cpp) has data races - see issue 1 created 2 years ago
* Other 6 libraries (including [nano-signal-slot](https://github.com/NoAvailableAlias/nano-signal-slot)) has potential deadlock issue - i've created issues in all these libraries

![default](https://user-images.githubusercontent.com/1856842/44581220-805fbb00-a7a5-11e8-8c54-6138c1fdcc35.png)

Can you please add notes for libraries that still has open issues with multithreading?

**Comment by NoAvailableAlias** [comment]
Well this is not good considering that boost::signals2 is failing the validation step of the benchmarks. I have only updated a few libs after they were initially added so was not aware of the open Kosta signals issue. 

I will create new readme sections concerning these issues. An additional section will be created encouraging library maintainers to fork this project in order to keep their libs up to date.

**Comment by i42output** [comment]
_neolib event system_ (né _neosigslot_) no longer deadlocks!!! \o/ What a kerfuffle it was sorting that out. :D

**Comment by sergey-shambir** [comment]
Looks like yet one library fixed known threading issues: https://github.com/Kosta-Github/signals-cpp/issues/8#event-1830051746

**Comment by NoAvailableAlias** [comment]
Thanks for the notification. I have updated the Kosta signals-cpp lib and results.

**Comment by NoAvailableAlias** [comment]
I have updated nano-signal-slot and have updated the benchmark results in the rework branch. I have also added the CppFakeIt LibFastSignals to the benchmark rework branch as well.

[Here are the results](https://github.com/NoAvailableAlias/signal-slot-benchmarks/tree/rework/results_msvc)

**Comment by NoAvailableAlias** [comment]
Another lib updated.
https://github.com/palacaze/sigslot/issues/1
Although I haven't looked through it to see if there are potential races due to the deadlock fix change.

**Comment by palacaze** [comment]
I just created a pull request with a new version that fixes this issue.
