### ISSUE TITLE
No longer builds with latest neolib signals

### ISSUE THREAD

**Issue by i42output** [NoAvailableAlias/signal-slot-benchmarks#16]
Hi,

No longer builds with latest neolib signals (neosigslot) which has been totally re-written with new data structures.  I will try to make a pull request if I can find the time. :D

/Leigh

**Comment by NoAvailableAlias** [comment]
Hello, I'll keep a lookout for it.

**Comment by NoAvailableAlias** [comment]
Replaced by #33
