### ISSUE TITLE
Simple signal "High performance C++11 signals"

### ISSUE THREAD

**Issue by billyquith** [NoAvailableAlias/signal-slot-benchmarks#3]
Just came across this one not on the list. https://github.com/larspensjo/SimpleSignal

Useful work!

**Comment by NoAvailableAlias** [comment]
Hmm, it might have been I was turned off when looking at this implementation two whole years ago...

I will get this lib added. However, it will require the use of the "Slot Scope" utility for automatically disconnecting slots. In this case it would disconnect size_t.

Will close this issue when complete.
