### ISSUE TITLE
Add vdksoft signals to the test set

### ISSUE THREAD

**Issue by delaitre** [NoAvailableAlias/signal-slot-benchmarks#4]
Can be found here: https://github.com/vdksoft/signals
Note that there is a thread safe version (default) and non thread safe one (by defining `VDK_SIGNALS_LITE`)

**Comment by NoAvailableAlias** [comment]
Thanks for the contribution. Currently the structure of the project doesn't support testing both thread/non-thread safe at once and I opt for testing the thread safe versions. I will update and close this once I get updated metrics pushed.

**Comment by NoAvailableAlias** [comment]
The vdksoft signals lib has been added to the rework branch by pulling from your signal-slot-benchmarks fork.

Thanks for the contribution!

I'll close this issue once the rework branch is ready for integration into the master branch.
